# Generated by Django 2.2 on 2019-04-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_postfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='company_id',
        ),
    ]
